### ISSUE TITLE
공부하다가 문의드립니다.

### ISSUE THREAD

**Issue by wooheaven** [Curt-Park/handwritten_digit_recognition#1]
https://tykimos.github.io/2017/06/10/Model_Save_Load/ 를 참고하여서
 
공유해주신 Resnet164 을 load 하고

1만개의 테스트셋 (x_test, y_test) 에 대하여 평가해보려고 했는데 

다음과 같은 에러를 만났습니다.

입력데이터의 shape 이 다르기 때문일 것 같습니다.

혹시 공유해주신 Resnet164를 위의 1만개의 테스트셋으로 평가하는 방법을 알려주실 수 있나요 ?

![2018-01-09 18 44 52](https://user-images.githubusercontent.com/5581657/34714739-b972fa14-f56d-11e7-8fe5-863871834fa4.png)

**Comment by Curt-Park** [comment]
안녕하세요.
input data의 shape을 (batch, height, width, channels) 형태로 변경해주시면 될 것 같습니다.
사용하시는 데이터의 경우에는 (10000, 28, 28, 1)의 형태가 되겠네요.

**Comment by wooheaven** [comment]
답변 감사드립니다.
